# Generated by Django 5.0.6 on 2024-06-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_customfile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfile',
            options={'ordering': ('user',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Список всех файлов'},
        ),
    ]
